#!/bin/bash

# wmtxt plugin: displays Weather Heat
# This script must be copied to: /usr/local/bin
# command:
### Testing:
# wmtext -i 3600 -b '#2f2f2f' -f '#c0c0c0' ./meteo4wmtext
### Prod:
# wmtext -i 3600 -b '#2f2f2f' -f '#c0c0c0' /usr/local/bin/meteo4wmtext

# Gets weather Heat from Wttr.in

### Functions
METEO_TOOLS=/usr/local/bin/functions_meteo.sh
#METEO_TOOLS=$HOME/SOURCES/agnostep-desktop/build/agnostep-theme/install/SCRIPTS/functions_meteo.sh
if [ ! -f $METEO_TOOLS ];then
	exit 1
fi
. $METEO_TOOLS

HEAT=""
WIND=""
RAIN=""
SNOW=""

LG=${LANG:0:2}
case "$LG" in
"fr")
TITLE="Météo"
LABEL3="Pluie"
LABEL4="Neige"
LABEL5="Sec";;
"en"|*)
TITLE="Weather"
LABEL3="Rain"
LABEL4="Snow"
LABEL5="Dry";;
esac
### We get the STATION vars:
fetch_meteo

L0="Meteo"
L1="$HEAT °C"
L2="${WIND%.00} km/h"
if [ "$RAIN" == "0.00" ] && [ "SNOW" == "0.00" ];then
	L3="- $LABEL5"
	L4=""
else
	L3="${LABEL3}: ${RAIN%.00} mm"
	L4="${LABEL4}: ${SNOW%.00} mm"
fi

echo -e "\t$L1 - $L2 \n\t$L3 - $L4"
