#!/bin/bash

####################################################
### A G N o S t e p  -  Desktop - by Patrick Cardona
### pcardona34 @ Github
###
### Thanks for the GNUstep Developers Community
### This is Free and Open Source software.
### Read License in the root directory.
####################################################

################################
### ScreenShot easy tool...
################################

function show_help
{
clear
printf "\nSyntaxe:\n"
printf "\t$0 <NAME> <DELAY> <EXT>\n"
printf "By default:\n"
printf "\tDELAY: 5 (sec)\n"
printf "\tEXT: tiff - Maybe: png, jpg.\n\n"
}
#################################

if [ $# -eq 0 ];then
	show_help
	exit 1
else
	NAME="$1"
	DELAY=${2:-5}
	EXT=${3:-tiff}
fi

scrot -c -p -d ${DELAY} -F ${NAME}.${EXT}
mv -fv ${NAME}.${EXT} $HOME/Images/
