#!/bin/bash

####################################################
### A G N o S t e p  -  Updater - by Patrick Cardona
### pcardona34 @ Github
###
### This is Free and Open Source software.
### Read License in the root directory.
####################################################

################################
### Upgrade
################################

################################
### VARS

LG=${LANG:0:2}
BELL=/usr/local/share/icons/bell.tif
. $HOME/.config/agnostep/flavour.conf
### A flag for C5C Agnostep Flavour
FLAG=$HOME/.UPDATER

###############################################
### Functions
###############################################
. /usr/local/bin/colors.sh

###################################################
### Update: check packages to update
###################################################

function update
{
#DELAY=10 # seconds

case "$LG" in
	"fr")
	TITLE="Mise à jour du Système Debian"
	MSG="nouveaux paquets disponibles."
	OK="Votre système est à jour."
	ITEM1="Mettre à jour"
	ITEM2="Ne rien faire";;
	"en" | *)
	TITLE="Debian System Updater"
	MSG="new packages available."
	OK="Your Operating System is up to date."
	JOB="Installing new packages..."
	ITEM1="Do Upgrade"
	ITEM2="Do Nothing";;
esac

### Search if upgradable packages exists
### We must substract one line of warning emitted by apt within a script
NB=$(( $(apt list --upgradable | wc -l) - 1 ))

### Uncomment the below lines for debug purpose only
#echo "NUMBER: $NB"
#read -p "pause" R
#echo "$FLAVOUR"

if [ $NB -gt 0 ];then
	if [ "$FLAVOUR" == "c5c" ];then
		#touch $FLAG
		echo "NB=${NB}" > $FLAG
	else
		ANSWER=$(dunstify -u critical -i $BELL --action "UPGRADE","$ITEM1" --action "EXIT","$ITEM2" "$TITLE" "$NB $MSG")
		case "$ANSWER" in
			"2"|"EXIT") exit 0;;
			"UPGRADE")
			cd $HOME && Updater --upgrade;;
		esac
	fi
else
	if [ "$FLAVOUR" == "c5c" ];then
		if [ -f $FLAG ];then
			rm -f $FLAG
		fi
	else
		dunstify "$TITLE" "$OK"
	fi
fi
}
### End of update

#######################################
function upgrade
{

case $PREFIX in
        "fr")
        TITLE="Mise à jour du Système Debian"
        MSG="Installation de nouveaux paquets..."
        OK="Votre système est à jour.";;
        "en" | *)
        TITLE="Debian System Updater"
        MSG="Installing new packages..."
        OK="Your Operating System is up to date.";;
esac

ID=$(dunstify "$TITLE" "$MSG" -t 0 -i $BELL -p)
sudo apt -y upgrade && sudo apt -y full-upgrade

if [ $? -eq 0 ];then
	dunstify -C $ID
	dunstify "$TITLE" "$OK" -i $BELL
	update
else
	echo "Update: Error!!!"
fi
}

### End of upgrade

######################################
### main script

upgrade
