#!/bin/bash

# wmtxt plugin: displays Weather Heat
# This script must be copied to: /usr/local/bin
# command:
### Testing:
# wmtext -i 3600 -b '#2f2f2f' -f '#c0c0c0' ./meteo4wmtext
### Prod:
# wmtext -i 3600 -b '#2f2f2f' -f '#c0c0c0' /usr/local/bin/meteo4wmtext

# Gets weather Heat from Wttr.in

### We get the STATION var:
CONF=$HOME/.config/agnostep/meteo.conf
if [ -f $CONF ];then
	. $CONF
else
	exit 1
fi

HEAT=`curl "wttr.in/${STATION}?m&format=1" | awk '{print $2}'`
SITE=`echo $STATION | awk -F, '{print $1}'`

LG=${LANG:0:2}
case "$LG" in
"fr")
	DATE=$(date +"%a%d/%m")
"en"|*)
	DATE=$(date +"%a %d/%m")
esac

L1="$DATE"
L2=" "
L3="${SITE:0:9}"
L4="  $HEAT"

echo $L1
echo $L2
echo $L3
echo $L4
